import type { GeneratedSample } from "@tidal/shared";

export interface ReportData {
  experimentId: string;
  configYAML: string;
  metrics: {
    finalLoss: number | null;
    finalPerplexity: number | null;
    totalSteps: number | null;
    trainingStatus: string | null;
  };
  checkpoints: Array<{
    filename: string;
    phase: string;
    epoch?: number;
  }>;
  samples: GeneratedSample[];
  rlMetrics: {
    episodeCount: number;
    finalReward: number | null;
  } | null;
}

function escapeHTML(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function generateHTMLReport(data: ReportData): string {
  const metricRow = (label: string, value: string | number | null) =>
    value != null
      ? `<tr><td style="padding:4px 12px;color:#9ca3af">${label}</td><td style="padding:4px 12px;font-family:monospace">${value}</td></tr>`
      : "";

  const checkpointRows = data.checkpoints
    .map(
      (c) =>
        `<tr><td style="padding:4px 12px;font-family:monospace">${escapeHTML(c.filename)}</td><td style="padding:4px 12px">${c.phase}</td><td style="padding:4px 12px">${c.epoch ?? "-"}</td></tr>`,
    )
    .join("\n");

  const sampleBlocks = data.samples
    .map(
      (s) => `
    <div style="background:#1f2937;border-radius:8px;padding:12px;margin-bottom:8px">
      <div style="color:#9ca3af;font-size:12px;margin-bottom:4px">Prompt${s.temperature ? ` (T=${s.temperature})` : ""}</div>
      <div style="font-family:monospace;font-size:13px;margin-bottom:8px">${escapeHTML(s.prompt)}</div>
      <div style="border-top:1px solid #374151;padding-top:8px">
        <div style="color:#9ca3af;font-size:12px;margin-bottom:4px">Generated</div>
        <div style="font-family:monospace;font-size:13px;white-space:pre-wrap">${escapeHTML(s.generated)}</div>
      </div>
    </div>`,
    )
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Experiment Report: ${escapeHTML(data.experimentId)}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0a0a0a; color: #e5e7eb; max-width: 900px; margin: 0 auto; padding: 24px; }
  h1 { font-size: 24px; border-bottom: 1px solid #374151; padding-bottom: 12px; }
  h2 { font-size: 18px; color: #9ca3af; margin-top: 32px; }
  table { border-collapse: collapse; width: 100%; }
  th { text-align: left; padding: 4px 12px; color: #6b7280; font-size: 12px; text-transform: uppercase; }
  pre { background: #1f2937; border-radius: 8px; padding: 16px; overflow-x: auto; font-size: 12px; line-height: 1.6; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; background: #374151; }
</style>
</head>
<body>
<h1>Experiment Report</h1>
<p style="font-family:monospace;color:#60a5fa">${escapeHTML(data.experimentId)}</p>
<p style="color:#6b7280;font-size:13px">Generated ${new Date().toISOString()}</p>

<h2>Metrics Summary</h2>
<table>
${metricRow("Status", data.metrics.trainingStatus)}
${metricRow("Total Steps", data.metrics.totalSteps?.toLocaleString() ?? null)}
${metricRow("Final Loss", data.metrics.finalLoss?.toFixed(4) ?? null)}
${metricRow("Final Perplexity", data.metrics.finalPerplexity?.toFixed(2) ?? null)}
${data.rlMetrics ? metricRow("RL Episodes", data.rlMetrics.episodeCount) : ""}
${data.rlMetrics?.finalReward != null ? metricRow("Final RL Reward", data.rlMetrics.finalReward.toFixed(4)) : ""}
</table>

${data.configYAML ? `<h2>Configuration</h2>\n<pre>${escapeHTML(data.configYAML)}</pre>` : ""}

<h2>Checkpoints</h2>
${
  data.checkpoints.length > 0
    ? `<table><thead><tr><th>Filename</th><th>Phase</th><th>Epoch</th></tr></thead><tbody>${checkpointRows}</tbody></table>`
    : "<p style='color:#6b7280'>No checkpoints</p>"
}

${
  data.samples.length > 0
    ? `<h2>Sample Outputs</h2>\n${sampleBlocks}`
    : ""
}

<hr style="border-color:#374151;margin-top:40px">
<p style="color:#6b7280;font-size:12px">Generated by Tidal Dashboard</p>
</body>
</html>`;
}

export function generateMarkdownReport(data: ReportData): string {
  const lines: string[] = [];

  lines.push(`# Experiment Report: ${data.experimentId}`);
  lines.push("");
  lines.push(`*Generated ${new Date().toISOString()}*`);
  lines.push("");

  lines.push("## Metrics Summary");
  lines.push("");
  lines.push("| Metric | Value |");
  lines.push("|--------|-------|");
  if (data.metrics.trainingStatus)
    lines.push(`| Status | ${data.metrics.trainingStatus} |`);
  if (data.metrics.totalSteps != null)
    lines.push(
      `| Total Steps | ${data.metrics.totalSteps.toLocaleString()} |`,
    );
  if (data.metrics.finalLoss != null)
    lines.push(`| Final Loss | ${data.metrics.finalLoss.toFixed(4)} |`);
  if (data.metrics.finalPerplexity != null)
    lines.push(
      `| Final Perplexity | ${data.metrics.finalPerplexity.toFixed(2)} |`,
    );
  if (data.rlMetrics) {
    lines.push(`| RL Episodes | ${data.rlMetrics.episodeCount} |`);
    if (data.rlMetrics.finalReward != null)
      lines.push(
        `| Final RL Reward | ${data.rlMetrics.finalReward.toFixed(4)} |`,
      );
  }
  lines.push("");

  if (data.configYAML) {
    lines.push("## Configuration");
    lines.push("");
    lines.push("```yaml");
    lines.push(data.configYAML);
    lines.push("```");
    lines.push("");
  }

  lines.push("## Checkpoints");
  lines.push("");
  if (data.checkpoints.length > 0) {
    lines.push("| Filename | Phase | Epoch |");
    lines.push("|----------|-------|-------|");
    for (const c of data.checkpoints) {
      lines.push(`| \`${c.filename}\` | ${c.phase} | ${c.epoch ?? "-"} |`);
    }
  } else {
    lines.push("No checkpoints available.");
  }
  lines.push("");

  if (data.samples.length > 0) {
    lines.push("## Sample Outputs");
    lines.push("");
    for (const s of data.samples) {
      lines.push(
        `### Prompt${s.temperature ? ` (T=${s.temperature})` : ""}`,
      );
      lines.push("");
      lines.push(`> ${s.prompt}`);
      lines.push("");
      lines.push("**Generated:**");
      lines.push("");
      lines.push("```");
      lines.push(s.generated);
      lines.push("```");
      lines.push("");
    }
  }

  lines.push("---");
  lines.push("*Generated by Tidal Dashboard*");

  return lines.join("\n");
}
